plugins {
    id 'com.android.application'
}

android {
    namespace 'com.kai.mousetouchplus'
    compileSdk 35

    defaultConfig {
        applicationId 'com.kai.mousetouchplus'
        minSdk 24
        targetSdk 35
        versionCode 14
        versionName '1.4'
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}
